---
title: "Plan B"
author: "Sherin Manish"
date: "7/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(GGally)
library(psych)

```

```{r}
hapdat<- read_xlsx("./happiness.xlsx")
hapdat
```

## Summary

```{r echo = TRUE, warning=FALSE,message=FALSE}

summary(hapdat)

```

### Selection Of variables

```{r echo = FALSE, warning=FALSE,message=FALSE}
library(tinytex)
library(readr)
colnames(hapdat)
ColumnSelected = c(1:3,7:12) 
Happy.df = hapdat[,ColumnSelected]

```

### Dependent Vs Independent Variables
```{r echo = FALSE, warning=FALSE,message=FALSE}
DV = Happy.df[,3]
IV = Happy.df[,4:9]

```

### PLOT 1


```{r  echo = TRUE, warning=FALSE,message=FALSE}
ggpairs(Happy.df[,2:9], mapping = ggplot2::aes(colour=Happy.df$`Regional indicator`), 
        lower = list(continuous = wrap("smooth", alpha = 0.3, size=0.1)))

```

## Plot2

```{r echo = TRUE, warning=FALSE,message=FALSE}
par(mfrow=c(1,2))
hist(Happy.df$`Social support`)

```

## Plot

```{r echo = TRUE, warning=FALSE,message=FALSE}
fit <- princomp(IV, cor=TRUE)
summary(fit)
loadings(fit) 
plot(fit,type="lines") 
fit$scores 
library(ggfortify)
autoplot(fit)

```

### Plot4

```{r echo = TRUE, warning=FALSE,message=FALSE}
Score <- fit$scores[,1:2]
plot(Score ,type="n") 
text(Score ,labels=names(IV),cex=.7) 

```

### Plot5

```{r echo = TRUE, warning=FALSE,message=FALSE}
Score <- factanal(IV, 3, rotation="varimax")
print(Score, digits=2, cutoff=.3, sort=TRUE)

```

### A vector countaining  3 regions

```{r echo = TRUE, warning=FALSE,message=FALSE}
RegionSelected = c("East Asia","Middle East and North Africa","Sub-Saharan Africa")
ImpoReg <- Happy.df %>% filter(`Regional indicator` %in% RegionSelected)
ggpairs(ImpoReg[,2:9], mapping = ggplot2::aes(colour=ImpoReg$`Regional indicator`), 
        lower = list(continuous = wrap("smooth", alpha = 0.3, size=0.1)))
```

### A vector countaining  1 region

```{r echo = TRUE, warning=FALSE,message=FALSE}
Region = c("Middle East and North Africa")
MENA <- Happy.df %>% filter(`Regional indicator` %in% Region)
ggpairs(MENA[,2:9], mapping = ggplot2::aes(colour=MENA$`Regional indicator`), 
        lower = list(continuous = wrap("smooth", alpha = 0.3, size=0.1)))
```